namespace BitBarons.AutoGenerated
{
    public static class MathOperations 
    {
        public static string Add(UnityEngine.Vector2 a, UnityEngine.Vector2 b)
        {
            return (a + b).ToString();
        }
        public static string Divide(float a, int b)
        {
            return (a / b).ToString();
        }
        public static string Add(float a, int b)
        {
            return (a + b).ToString();
        }
        public static string Add(float a, float b)
        {
            return (a + b).ToString();
        }
        public static string Add(byte a, int b)
        {
            return (a + b).ToString();
        }
        public static string Add(int a, int b)
        {
            return (a + b).ToString();
        }
        public static string Subtract(float a, float b)
        {
            return (a - b).ToString();
        }
        public static string Add(float a, byte b)
        {
            return (a + b).ToString();
        }
        public static string Add(float a, string b)
        {
            return (a + b).ToString();
        }
        public static string Multiply(byte a, byte b)
        {
            return (a * b).ToString();
        }
        public static string Divide(int a, int b)
        {
            return (a / b).ToString();
        }
        public static string Multiply(byte a, float b)
        {
            return (a * b).ToString();
        }
        public static string Subtract(UnityEngine.Vector3 a, UnityEngine.Vector3 b)
        {
            return (a - b).ToString();
        }
        public static string Add(UnityEngine.Vector4 a, UnityEngine.Vector4 b)
        {
            return (a + b).ToString();
        }
        public static string Modulo(float a, float b)
        {
            return (a % b).ToString();
        }
        public static string Multiply(float a, byte b)
        {
            return (a * b).ToString();
        }
        public static string Subtract(int a, float b)
        {
            return (a - b).ToString();
        }
        public static string Modulo(byte a, byte b)
        {
            return (a % b).ToString();
        }
        public static string Subtract(byte a, byte b)
        {
            return (a - b).ToString();
        }
        public static string Multiply(int a, int b)
        {
            return (a * b).ToString();
        }
    }
}
