// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_master_x = "CgkI9sTWxdYBEAIQDA"; // <GPGSID>
        public const string achievement_the_detective = "CgkI9sTWxdYBEAIQAA"; // <GPGSID>
        public const string achievement_mister_x = "CgkI9sTWxdYBEAIQAQ"; // <GPGSID>
        public const string achievement_driver = "CgkI9sTWxdYBEAIQBQ"; // <GPGSID>
        public const string achievement_theres_nothing_better_than_the_tube = "CgkI9sTWxdYBEAIQBw"; // <GPGSID>
        public const string achievement_undercover_agent = "CgkI9sTWxdYBEAIQAg"; // <GPGSID>
        public const string achievement_rookie = "CgkI9sTWxdYBEAIQCA"; // <GPGSID>
        public const string achievement_the_shadow = "CgkI9sTWxdYBEAIQAw"; // <GPGSID>
        public const string achievement_gotcha = "CgkI9sTWxdYBEAIQBA"; // <GPGSID>
        public const string achievement_bames_jond = "CgkI9sTWxdYBEAIQDQ"; // <GPGSID>
        public const string achievement_society = "CgkI9sTWxdYBEAIQCQ"; // <GPGSID>
        public const string achievement_mi5 = "CgkI9sTWxdYBEAIQDg"; // <GPGSID>
        public const string achievement_specialist = "CgkI9sTWxdYBEAIQCw"; // <GPGSID>
        public const string achievement_sightseeing_tour = "CgkI9sTWxdYBEAIQBg"; // <GPGSID>
        public const string achievement_life_in_a_fast_lane = "CgkI9sTWxdYBEAIQCg"; // <GPGSID>

}

